Add Mastercard 3DS card (take #2)
adyen-examples/adyen-testcards-extension pull request #39
Opened 2024-01-25 09:59 UTC by sam-artuso

Reference: https://docs.adyen.com/development-resources/testing/test-card-numbers/#enrolled-in-3d-secure-2

2024-01-25 14:25 UTC, gcatanese requested changes
@sam-artuso Thanks for the PR. There is a small change required, we are then ready to merge. Next week we plan to release the new version.

Please remove the `WIP` tag when this is ready

2024-01-25 14:25 UTC, gcatanese commented on data/cards.json
> +              "cardNumber" : "5454 5454 5454 5454",
It should be `cardnumber`

2024-01-25 18:30 UTC, sam-artuso commented
Rebased on top of master and squashed my commits.

2024-01-26 08:01 UTC, merged

2024-01-26 08:01 UTC, gcatanese commented
Looks great, thank you!

2025-02-24 09:21 UTC, Spacebounddaily approved these changes